/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class one_papachi_fuse4j_Fuse4j */

#ifndef _Included_one_papachi_fuse4j_Fuse4j
#define _Included_one_papachi_fuse4j_Fuse4j
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     one_papachi_fuse4j_Fuse4j
 * Method:    mount
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_one_papachi_fuse4j_Fuse4j_mount
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
